name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-20.04
    steps:
     - name: Print Greeting
       run: echo "Hello World!"
     - name: Say Goodby
       run: echo "Goodby, stay save!"
